[build]
  command = "npm run build"
  publish = "build"

[context.production.environment]
  REACT_APP_WS_ENDPOINT = "wss://westend-rpc.polkadot.io"

[context.deploy-preview.environment]
  REACT_APP_WS_ENDPOINT = "wss://westend-rpc.polkadot.io"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200